// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp8eniS4INnGbGgdFg7Bl7jp7NHuL897g',
    appId: '1:776268132845:web:56d2fb53ec9a18abe8b7e4',
    messagingSenderId: '776268132845',
    projectId: 'new-conect-ca7f0',
    authDomain: 'new-conect-ca7f0.firebaseapp.com',
    storageBucket: 'new-conect-ca7f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQbsrvoFJLHMZp6G-mduuk3Uj1sRVi4Dc',
    appId: '1:776268132845:android:c06fa82c3f10150ae8b7e4',
    messagingSenderId: '776268132845',
    projectId: 'new-conect-ca7f0',
    storageBucket: 'new-conect-ca7f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTeGjmVGh39Z-WoaR5_uDy7quJxZbb8g',
    appId: '1:776268132845:ios:b801885766b31ba7e8b7e4',
    messagingSenderId: '776268132845',
    projectId: 'new-conect-ca7f0',
    storageBucket: 'new-conect-ca7f0.appspot.com',
    iosBundleId: 'com.example.localeConnectt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTeGjmVGh39Z-WoaR5_uDy7quJxZbb8g',
    appId: '1:776268132845:ios:b801885766b31ba7e8b7e4',
    messagingSenderId: '776268132845',
    projectId: 'new-conect-ca7f0',
    storageBucket: 'new-conect-ca7f0.appspot.com',
    iosBundleId: 'com.example.localeConnectt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp8eniS4INnGbGgdFg7Bl7jp7NHuL897g',
    appId: '1:776268132845:web:6eba1931b416a87be8b7e4',
    messagingSenderId: '776268132845',
    projectId: 'new-conect-ca7f0',
    authDomain: 'new-conect-ca7f0.firebaseapp.com',
    storageBucket: 'new-conect-ca7f0.appspot.com',
  );
}
